export { default as clone } from './clone';
export { default as cloneDeep } from './cloneDeep';
export { default as curried } from './curried';
export { default as equals } from './equals';
export { default as words } from './words';

export { default as is } from './is';
export { default as isArray } from './isArray';
export { default as isBigInt } from './isBigInt';
export { default as isBigIntPrimitive } from './isBigIntPrimitive';
export { default as isBoolean } from './isBoolean';
export { default as isBooleanPrimitive } from './isBooleanPrimitive';
export { default as isFalsy } from './isFalsy';
export { default as isFunction } from './isFunction';
export { default as isNonNull } from './isNonNull';
export { default as isNonNullish } from './isNonNullish';
export { default as isNonUndefined } from './isNonUndefined';
export { default as isNull } from './isNull';
export { default as isNullish } from './isNullish';
export { default as isNumber } from './isNumber';
export { default as isNumberPrimitive } from './isNumberPrimitive';
export { default as isNumeric } from './isNumeric';
export { default as isNumericPrimitive } from './isNumericPrimitive';
export { default as isObject } from './isObject';
export { default as isObjectLike } from './isObjectLike';
export { default as isPlainObject } from './isPlainObject';
export { default as isPrimitive } from './isPrimitive';
export { default as isString } from './isString';
export { default as isStringPrimitive } from './isStringPrimitive';
export { default as isSymbol } from './isSymbol';
export { default as isSymbolPrimitive } from './isSymbolPrimitive';
export { default as isTruthy } from './isTruthy';
export { default as isUndefined } from './isUndefined';

export type * from './words';

export type * from './isFalsy';
export type * from './isNonNull';
export type * from './isNonNullish';
export type * from './isNonUndefined';
export type * from './isPrimitive';
